# Team Yaml
coverage:
  round: up
  precision: 2
  status:
    project:
      default:
        target: 90%
        threshold: 2%
    numpy:
      target: 90%
      flags:
          - numpy
    pytorch:
      target: 40%
      flags:
          - pytorch
    tensorflow:
      target: 40%
      flags:
          - tensorflow

# Repository Yaml
coverage:
  round: up
  range: 50..80

# Files to ignore
ignore:
  - "examples/data"
  - "examples/imgs"
