coverage:
  round: up
  precision: 2
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        base: auto
       # advanced
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: False
        only_pulls: false
    patch:
      default:
        # basic
        target: 90%
        threshold: 2%
        base: auto
        # advanced
        branches:
          - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false

# Files to ignore
ignore:
  - "examples/data"
  - "examples/imgs"
