version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

dependency_file_paths = [
  "ci-requirements.txt",
  "dev-requirements.txt",
  "doc-requirements.txt",
  "opt-requirements.txt"
  "requirements.txt",
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
