version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]


[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "ci-requirements.txt",
  "dev-requirements.txt",
  "doc-requirements.txt",
  "opt-requirements.txt"
  "requirements.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
