name: Bug Report
description: Report a bug to help us improve
title: "Bug: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a Bug report. Please fill out the information below.
  - type: checkboxes
      id: Documentation
      attributes:
        label: Geomstats documentation.
        description: Please confirm that you read [geomstats documentation](https://geomstats.github.io/index.html) and could not find a solution for your problem there.
  - type: textarea
    attributes:
      label: Describe the bug.
      description: 'A clear and concise description of the bug.'
  - type: textarea
    attributes:
      label: Describe the steps to reproduce the behavior.
      description: 'Describe clearly and concisely the steps to ensure that it can be reproduced and potentially fixed'
  - type: textarea
    attributes:
      label: Expected behavior.
      description: 'A clear and concise description of what you expected to happen.'
  - type: textarea
    attributes:
      label: Screenshots.
      description: 'If applicable, add screenshots to help explain your problem.'
  - type: input
    attributes:
      label: Environment info
      description: 'Please describe what operating system and version you are using'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: 'Any additional information that may help us reproduce the bug.'

