name: Improve existing content
description: Make a suggestion about the Geomstats docs.
labels:
  - Docs
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve Geomstat's docs!        
        Please check to make sure that a similar [issue](https://github.com/geomstats/geomstats/labels/documentation) doesn't already exist and then fill out the form below.        
  - type: input
    attributes:
      label: Where should the content be modified?
      description: Please provide information (link) about the content's location.
    validations:
      required: false

  - type: textarea
    attributes:
      label: What should be modified?
      description: |
        Please propose how could the existing content be improved.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Add any more info or links that explain what you want to add.
    validations:
      required: false
