name: Benchmarks
on:
  push:
    branches: [master,github-actions-test]
  pull_request:
    branches: [master]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Benchmarking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies [pip]
        run:  |
          pip install --upgrade pip setuptools wheel
          for req in doc-requirements.txt opt-requirements.txt requirements.txt docs/requirements.txt; do
            pip install -q -r $req
          done
          pip install -e .

      - name: Run benchmark
        run: |
          cd benchmarks
          pytest bench.py --benchmark-json output.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: examples/pytest/output.json
          github-token: ${{ secrets.DOCUMENTATION_KEY }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@nmiolane'
